"""Traduções e constantes textuais usadas na aplicação.

Mantém os nomes originais (`PAISES_TRADUCAO` e `STATUS_TRADUCAO`) para compatibilidade
com as páginas existentes e expõe aliases em inglês para uso futuro.
"""

PAISES_TRADUCAO = {
    "United Kingdom": "Reino Unido",
    "Belgium": "Bélgica",
    "United States of America": "Estados Unidos da América",
    "Germany": "Alemanha",
    "Netherlands": "Países Baixos",
    "Thailand": "Tailândia",
    "Italy": "Itália",
    "France": "França",
    "Spain": "Espanha",
    "New Zealand": "Nova Zelândia",
    "Sweden": "Suécia",
    "Estonia": "Estônia",
    "Brazil": "Brasil",
    "Hungary": "Hungria",
    "Denmark": "Dinamarca",
    "Monaco": "Mônaco",
    "Canada": "Canadá",
    "Austria": "Áustria",
    "Argentina": "Argentina",
    "South Africa": "África do Sul",
    "Finland": "Finlândia",
    "Australia": "Austrália",
    "Switzerland": "Suíça",
    "Ireland": "Irlanda",
    "Portugal": "Portugal",
    "Uruguay": "Uruguai",
    "Venezuela": "Venezuela",
    "Mexico": "México",
    "India": "Índia",
    "Czechia": "República Tcheca",
    "Malaysia": "Malásia",
    "Hong Kong": "Hong Kong",
    "Japan": "Japão",
    "Indonesia": "Indonésia",
    "Colombia": "Colômbia",
    "Poland": "Polônia",
    "Russia": "Rússia",
    "Morocco": "Marrocos",
    "Zimbabwe": "Zimbábue",
    "China": "China",
    "Israel": "Israel",
    "Chile": "Chile",
    "Liechtenstein": "Liechtenstein",
    "Bahrain": "Bahrein",
    "Azerbaijan": "Azerbaijão",
    "Turkey": "Turquia",
    "Saudi Arabia": "Arábia Saudita",
    "South Korea": "Coreia do Sul",
    "Qatar": "Catar",
    "Singapore": "Singapura",
    "United Arab Emirates": "Emirados Árabes Unidos",
}

STATUS_TRADUCAO = {
    "Accident": "Acidente",
    "Accident damage": "Dano por acidente",
    "Accident in practice": "Acidente no treino",
    "Accident in qualifying": "Acidente na qualificação",
    "Accident in warm-up": "Acidente no aquecimento",
    "Accident on formation lap": "Acidente na volta de formação",
    "Additional brake fluid": "Fluido de freio adicional",
    "Airbox": "Caixa de ar",
    "Alternator": "Alternador",
    "Axle": "Eixo",
    "Battery": "Bateria",
    "Brake bias": "Balanceamento de freio",
    "Brakes": "Freios",
    "Broken floor": "Assoalho quebrado",
    "Broken wing": "Asa quebrada",
    "Camera car": "Carro câmera",
    "Camshaft": "Comando de válvulas",
    "Car damaged": "Carro danificado",
    "Car damaged in practice": "Carro danificado no treino",
    "Car damaged in qualifying": "Carro danificado na qualificação",
    "Car not ready": "Carro não pronto",
    "Car raced by Belsø": "Carro pilotado por Belsø",
    "Car raced by Beltoise": "Carro pilotado por Beltoise",
    "Car raced by Bondurant": "Carro pilotado por Bondurant",
    "Car raced by Bonnier": "Carro pilotado por Bonnier",
    "Car raced by Daigh": "Carro pilotado por Daigh",
    "Car raced by Fabi": "Carro pilotado por Fabi",
    "Car raced by Ganley": "Carro pilotado por Ganley",
    "Car raced by Gethin": "Carro pilotado por Gethin",
    "Car raced by Gregory": "Carro pilotado por Gregory",
    "Car raced by Gurney": "Carro pilotado por Gurney",
    "Car raced by Hailwood": "Carro pilotado por Hailwood",
    "Car raced by Hobbs": "Carro pilotado por Hobbs",
    "Car raced by Irwin": "Carro pilotado por Irwin",
    "Car raced by Jarier": "Carro pilotado por Jarier",
    "Car raced by Marko": "Carro pilotado por Marko",
    "Car raced by Patrese": "Carro pilotado por Patrese",
    "Car raced by Pirocchi": "Carro pilotado por Pirocchi",
    "Car raced by Posey": "Carro pilotado por Posey",
    "Car raced by Raby": "Carro pilotado por Raby",
    "Car raced by Rodríguez": "Carro pilotado por Rodríguez",
    "Car raced by Schenken": "Carro pilotado por Schenken",
    "Car raced by Surer": "Carro pilotado por Surer",
    "Car raced by Surtees": "Carro pilotado por Surtees",
    "Car raced by Trintignant": "Carro pilotado por Trintignant",
    "Car raced by Villoresi": "Carro pilotado por Villoresi",
    "Car seized by police": "Carro apreendido pela polícia",
    "Car underweight": "Carro abaixo do peso",
    "Car unraceworthy": "Carro indigno de correr",
    "Caused collision with Trulli": "Causou colisão com Trulli",
    "Chassis": "Chassis",
    "Clutch": "Embreagem",
    "Collision": "Colisão",
    "Collision damage": "Dano por colisão",
    "Compressor": "Compressor",
    "Coolant leak": "Vazamento de líquido de arrefecimento",
    "Cooling system": "Sistema de arrefecimento",
    "Crankshaft": "Comando de válvulas",
    "Differential": "Diferencial",
    "Distributor": "Distribuidor",
    "Driveshaft": "Eixo de transmissão",
    "Driveshaft hub": "Cubo do eixo de transmissão",
    "Drivetrain": "Trem de força",
    "Driving too slowly": "Dirigindo muito lentamente",
    "Electrical": "Elétrico",
    "Electronics": "Eletrônica",
    "Energy storage system failure": "Falha do sistema de armazenamento de energia",
    "Engine": "Motor",
    "Engine valve": "Válvula do motor",
    "Exhaust": "Escape",
    "Failed scrutineering": "Falha na verificação técnica",
    "Failed to serve stop-go penalty": "Falha em cumprir penalidade stop-go",
    "Fatal accident": "Acidente fatal",
    "Fatal accident in practice": "Acidente fatal no treino",
    "Fatal accident in qualifying": "Acidente fatal na qualificação",
    "Fatal accident in support race": "Acidente fatal em corrida de apoio",
    "Fatal collision": "Colisão fatal",
    "Fire": "Incêndio",
    "Fire extinguisher": "Extintor de incêndio",
    "Front wing": "Asa dianteira",
    "Fuel": "Combustível",
    "Fuel cell": "Célula de combustível",
    "Fuel injection": "Injeção de combustível",
    "Fuel leak": "Vazamento de combustível",
    "Fuel pipe": "Tubo de combustível",
    "Fuel pressure": "Pressão do combustível",
    "Fuel pump": "Bomba de combustível",
    "Fuel rig": "Equipamento de combustível",
    "Fuel sample": "Amostra de combustível",
    "Fuel system": "Sistema de combustível",
    "Gearbox": "Caixa de marchas",
    "Halfshaft": "Semieixo",
    "Handling": "Comportamento",
    "Hybrid system": "Sistema híbrido",
    "Hydraulics": "Hidráulica",
    "Ignition": "Ignição",
    "Ignored black flag": "Ignorou bandeira preta",
    "Ignored blue flags": "Ignorou bandeiras azuis",
    "Ignored red light": "Ignorou luz vermelha",
    "Ignored yellow flags": "Ignorou bandeiras amarelas",
    "Ignored yellow flags in practice": "Ignorou bandeiras amarelas no treino",
    "Illegal bodywork": "Carroçaria ilegal",
    "Illegal brake ducts": "Dutos de freio ilegais",
    "Illegal car change": "Mudança de carro ilegal",
    "Illegal car repairs": "Reparos no carro ilegais",
    "Illegal floor": "Assoalho ilegal",
    "Illegal front wing endplates": "Placas finais da asa dianteira ilegais",
    "Illegal fuel": "Combustível ilegal",
    "Illegal pit stop": "Parada nos boxes ilegal",
    "Illegal race entry": "Entrada na corrida ilegal",
    "Illegal rear wing": "Asa traseira ilegal",
    "Illegal skid block wear": "Desgaste de bloco de deslizamento ilegal",
    "Illegal start": "Saída ilegal",
    "Illegal tyre change": "Mudança de pneu ilegal",
    "Illegal undertray mounting": "Montagem de bandeja inferior ilegal",
    "Illness": "Doença",
    "Incorrect grid formation": "Formação de grid incorreta",
    "Incorrect starting procedure": "Procedimento de partida incorreto",
    "Injection": "Injeção",
    "Injury": "Lesão",
    "Injury in practice": "Lesão no treino",
    "KERS failure": "Falha do KERS",
    "Launch control": "Controle de saída",
    "Loose wheel": "Roda solta",
    "Magneto": "Magneto",
    "Mechanical": "Mecânico",
    "Mechenical": "Mecânico",
    "Misled stewards": "Comissários enganados",
    "Missed weight check": "Falha na verificação de peso",
    "Money dispute": "Disputa de dinheiro",
    "Oil leak": "Vazamento de óleo",
    "Oil line": "Linha de óleo",
    "Oil pipe": "Tubo de óleo",
    "Oil pressure": "Pressão do óleo",
    "Oil pump": "Bomba de óleo",
    "Out of fuel": "Sem combustível",
    "Overheating": "Superaquecimento",
    "Overtaking on formation lap": "Ultrapassagem na volta de formação",
    "Physical": "Físico",
    "Pit fire": "Incêndio nos boxes",
    "Pit stop issue": "Problema na parada nos boxes",
    "Pneumatics": "Pneumática",
    "Power loss": "Perda de potência",
    "Power steering": "Direção hidráulica",
    "Power unit": "Unidade de potência",
    "Practice only": "Apenas treino",
    "Puncture": "Furo",
    "Puncture damage": "Dano por furo",
    "Push start": "Partida empurrando",
    "Push start in pits": "Partida empurrando nos boxes",
    "Radiator": "Radiador",
    "Rear wing": "Asa traseira",
    "Received outside assistance": "Recebeu assistência externa",
    "Rejoined track illegally": "Retornou à pista ilegalmente",
    "Reserve driver": "Piloto reserva",
    "Retirement": "Aposentadoria",
    "Reversed in pits": "Inverteu nos boxes",
    "Safety belt": "Cinto de segurança",
    "Safety concerns": "Preocupações de segurança",
    "Seat": "Assento",
    "Spark plugs": "Velas de ignição",
    "Spin": "Rotação",
    "Spun off": "Saiu de pista",
    "Stalled": "Parou",
    "Starter": "Motor de partida",
    "Steering": "Direção",
    "Supercharger": "Supercompressor",
    "Suspension": "Suspensão",
    "Technical defect": "Defeito técnico",
    "Technical infringements": "Infrações técnicas",
    "Throttle": "Acelerador",
    "Track rod": "Barra de direção",
    "Traction control": "Controle de tração",
    "Transmission": "Transmissão",
    "Turbo": "Turbo",
    "Turbocharger": "Turbocompressor",
    "Tyre": "Pneu",
    "Tyre dispute": "Disputa de pneu",
    "Tyre shortage": "Escassez de pneu",
    "Tyre temperature": "Temperatura do pneu",
    "Undertray": "Bandeja inferior",
    "Unfit": "Impróprio",
    "Unwell": "Indisposto",
    "Vibrations": "Vibrações",
    "Water leak": "Vazamento de água",
    "Water pipe": "Tubo de água",
    "Water pressure": "Pressão da água",
    "Water pump": "Bomba de água",
    "Water radiator": "Radiador de água",
    "Wheel": "Roda",
    "Wheel bearing": "Rolamento da roda",
    "Wheel hub": "Cubo da roda",
    "Wheel nut": "Porca da roda",
    "Wheel rim": "Aro da roda",
    "Withdrew": "Desistiu",
    "Wrong tyres": "Pneus errados",
    "DNF": "Não terminou (DNF)",
    "DNP": "Não participou (DNP)",
    "DNPQ": "Não pré-qualificou (DNPQ)",
    "DNQ": "Não qualificou (DNQ)",
    "DNS": "Não largou (DNS)",
    "DSQ": "Desclassificado (DSQ)",
    "EX": "Excluído (EX)",
    "NC": "Não classificado (NC)",
    "Energy Recovery System": "Sistema de Recuperação de Energia",
    "Safety switch": "Interruptor de segurança",
    "Broken seat": "Assento quebrado",
}

COUNTRY_TRANSLATIONS = PAISES_TRADUCAO
STATUS_TRANSLATIONS = STATUS_TRADUCAO
FINISHED_STATUS = "Concluiu a prova"
DID_NOT_START_STATUSES = {
    "Não largou (DNS)",
    "Não qualificou (DNQ)",
    "Não pré-qualificou (DNPQ)",
    "Não participou (DNP)",
    "Desistiu",
}
